# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Gibbs algorithm with Rcpp.
#' @description To generate two chains 'x' and 'y' using Gibbs algorithm with Rcpp. 
#' @param N the number of samples
#' @param n0 parameter of original distribution
#' @param a0 parameter of original distribution
#' @param b0 parameter of original distribution
#' @param mu1 initial value of 'x' when generating
#' @param mu2 initial value of 'y' when generating
#' @return Return the generated chain of 'x' and 'y'
#' @importFrom stats rbeta rbinom
#' @examples
#' \dontrun{
#' N <- 5000
#' b <- 1000
#' mu1 <- 1
#' mu2 <- 0.6 
#' n0 <- 20
#' a0 <- 7
#' b0 <- 10
#' resultC <- gibbsC(N, a0, b0, n0, mu1, mu2)
#' }
#' @export
gibbsC <- function(N, a0, b0, n0, mu1, mu2) {
    .Call('_StatComp21022_gibbsC', PACKAGE = 'StatComp21022', N, a0, b0, n0, mu1, mu2)
}

